### PR TITLE
Add install target to Makefile

### PR DESCRIPTION
**Pull request by kirbyfan64**
This is just a simple utility thing.

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Bump?

**Comment by kirbyfan64** [comment]
@mapbox Guess...really...

**Comment by springmeyer** [comment]
@kirbyfan64 - hi, thanks for the contribution. However I'm not seeing the benefit of having an install target. These programs are not general purpose utilities - they are rather testing programs that work fine locally.

**Comment by kirbyfan64** [comment]
@springmeyer If you felt that way, you could've just told me to close it to begin with... ;)

**Comment by springmeyer** [comment]
@kirbyfan64 - I'm sorry, I did not see the ticket until just now.

**Pull request closed without merging**
