### PR TITLE
Visitor no copy

### PR DESCRIPTION
**Pull request by artemp**
ref https://github.com/mapbox/variant/issues/71

### CODE REVIEW

**Comment by lightmare** [comment]
Should've posted this here instead https://github.com/mapbox/variant/issues/71#issuecomment-175579777

**Comment by lightmare** [comment]
After thinking about it a bit more, why does `dispatcher` have template parameter `F` in the first place? Pushing it down to `apply*` functions would simplify forwarding:
```c++
template <typename V, typename R, typename T, typename... Types>
struct dispatcher<V, R, T, Types...>
{
    using result_type = R;
    template <typename F>
    VARIANT_INLINE static result_type apply_const(V const& v, F && f)
    {
        //if (v.get_type_index() == sizeof...(Types))
        if (v. template is<T>())
        {
            // not sure whether here std::forward<F>(f) should be used
            return f(unwrapper<T>::apply_const(v. template get<T>()));
        }
        else
        {
            return dispatcher<V, R, Types...>::apply_const(v, std::forward<F>(f));
        }
    }

    template <typename F>
    VARIANT_INLINE static result_type apply(V & v, F && f)
    {
        if (v. template is<T>())
        {
            // not sure whether here std::forward<F>(f) should be used
            return f(unwrapper<T>::apply(v. template get<T>()));
        }
        else
        {
            return dispatcher<V, R, Types...>::apply(v, std::forward<F>(f));
        }
    }
};

// variant::visit
    template <typename F, typename V,
              typename R = typename detail::result_of_unary_visit<F && , first_type>::type>
    auto VARIANT_INLINE
    static visit(V const& v, F && f)
        -> decltype(detail::dispatcher<V, R, Types...>::apply_const(v, std::forward<F>(f)))
    {
        return detail::dispatcher<V, R, Types...>::apply_const(v, std::forward<F>(f));
    }
```

I'd also swap template parameters, making it `detail::dispatcher<R, V, Types...>`

**Comment by lightmare** [comment]
Edited the above snippet, `std::forward<F>(f)` must be used before call as well, otherwise overloading on function ref-qualifiers doesn't work.

**Comment by tomilov** [comment]
For testing of perfect forwarding of visitor and arguments to visitor I would like to offer [this test](https://github.com/tomilov/variant/blob/master/test/include/test/visit.hpp).

**Pull request merged**
